# Generated by Django 5.1.7 on 2025-06-14 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя пользователя')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='media/users/')),
                ('client', models.CharField(max_length=100, verbose_name='Клиент')),
                ('stars', models.SmallIntegerField(verbose_name='Кол-во звезд')),
                ('description', models.TextField(verbose_name='Отзыв')),
            ],
        ),
    ]
