# Generated by Django 5.1.7 on 2025-06-14 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_rename_description_review_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='stars',
            field=models.DecimalField(decimal_places=1, max_digits=2, verbose_name='Рейтинг'),
        ),
    ]
