# Generated by Django 5.1.7 on 2025-06-16 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_alter_review_stars'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='client',
        ),
    ]
